Reduced required versions on the following libraries. libfontconfig 2.3.1 to 2.2.3 libpango 1.10.2 to 1.10.1 libxcursor 1.1.3 to 1.1.2 DP
git-svn-id: https://gpsdrive.svn.sourceforge.net/svnroot/gpsdrive/trunk@822 e3ca9d6f-f84a-410d-b97a-e7ddc331358d

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12790,6 +12790,7 @@ else
   HAVE_GDAL_FALSE=
 fi
 
+GDAL_LIBS=`gdal-config --libs`
 
 
 # Check whether --enable-shared or --disable-shared was given.
@@ -13396,7 +13397,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 13399 "configure"' > conftest.$ac_ext
+  echo '#line 13400 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -14516,7 +14517,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:14519:" \
+echo "$as_me:14520:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -15577,11 +15578,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15580: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15581: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15584: \$? = $ac_status" >&5
+   echo "$as_me:15585: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15845,11 +15846,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15848: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15849: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15852: \$? = $ac_status" >&5
+   echo "$as_me:15853: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15949,11 +15950,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15952: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15953: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15956: \$? = $ac_status" >&5
+   echo "$as_me:15957: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18307,7 +18308,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18310 "configure"
+#line 18311 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18407,7 +18408,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18410 "configure"
+#line 18411 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -20745,11 +20746,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20748: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20749: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:20752: \$? = $ac_status" >&5
+   echo "$as_me:20753: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -20849,11 +20850,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20852: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20853: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:20856: \$? = $ac_status" >&5
+   echo "$as_me:20857: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22437,11 +22438,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:22440: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:22441: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:22444: \$? = $ac_status" >&5
+   echo "$as_me:22445: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -22541,11 +22542,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:22544: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:22545: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:22548: \$? = $ac_status" >&5
+   echo "$as_me:22549: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -24764,11 +24765,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:24767: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:24768: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:24771: \$? = $ac_status" >&5
+   echo "$as_me:24772: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -25032,11 +25033,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:25035: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:25036: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:25039: \$? = $ac_status" >&5
+   echo "$as_me:25040: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -25136,11 +25137,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:25139: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:25140: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:25143: \$? = $ac_status" >&5
+   echo "$as_me:25144: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -31120,7 +31121,7 @@ fi
 echo checking for package libexpat1... TODO >&2
 
 echo -n checking for package libfontconfig1...
-if $PKG_CONFIG fontconfig --atleast-version=2.3.1
+if $PKG_CONFIG fontconfig --atleast-version=2.2.3
 then
    echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
@@ -31203,22 +31204,22 @@ else
 fi
 
 else
-   { { echo "$as_me:$LINENO: error: libfontconfig is missing or your version is to old. Min Version 2.3.1" >&5
-echo "$as_me: error: libfontconfig is missing or your version is to old. Min Version 2.3.1" >&2;}
+   { { echo "$as_me:$LINENO: error: libfontconfig is missing or your version is to old. Min Version 2.2.3" >&5
+echo "$as_me: error: libfontconfig is missing or your version is to old. Min Version 2.2.3" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 echo checking for package libfreetype6... TODO >&2
 echo TODO checking for package libgcc1... TODO >&2
 
-echo -n checking for package libpango1 1.0...
-if $PKG_CONFIG pango --atleast-version=1.10.2
+echo -n checking for package libpango1 1.10...
+if $PKG_CONFIG pango --atleast-version=1.10.1
 then
     echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
                 else
-    { { echo "$as_me:$LINENO: error: libpango1 is missing or your version is to old. Min Version 1.10.2" >&5
-echo "$as_me: error: libpango1 is missing or your version is to old. Min Version 1.10.2" >&2;}
+    { { echo "$as_me:$LINENO: error: libpango1 is missing or your version is to old. Min Version 1.10.1" >&5
+echo "$as_me: error: libpango1 is missing or your version is to old. Min Version 1.10.1" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -31235,10 +31236,8 @@ fi
 
 echo checking for package libstdc++6... TODO >&2
 echo checking for package libx11-6...   TODO >&2
-echo checking for package libxcursor1... TODO >&2
-
 echo -n checking for package libxcursor1...
-if $PKG_CONFIG xcursor --atleast-version=1.1.3
+if $PKG_CONFIG xcursor --atleast-version=1.1.2
 then
     echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
@@ -31321,8 +31320,8 @@ else
 fi
 
 else
-    { { echo "$as_me:$LINENO: error: libxcursor1 is missing or your version is to old. Min Version 1.1.3" >&5
-echo "$as_me: error: libxcursor1 is missing or your version is to old. Min Version 1.1.3" >&2;}
+    { { echo "$as_me:$LINENO: error: libxcursor1 is missing or your version is to old. Min Version 1.1.2" >&5
+echo "$as_me: error: libxcursor1 is missing or your version is to old. Min Version 1.1.2" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -32133,7 +32132,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 32136 "configure"
+#line 32135 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -40235,7 +40234,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 40238 "configure"
+#line 40237 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
