test that temp files were created properly
git-svn-id: https://gpsdrive.svn.sourceforge.net/svnroot/gpsdrive/trunk@2203 e3ca9d6f-f84a-410d-b97a-e7ddc331358d

diff --git a/scripts/geo-code b/scripts/geo-code
--- a/scripts/geo-code
+++ b/scripts/geo-code
@@ -254,6 +254,10 @@ remove_cruft() {
 #	Main Program
 #
 TMP=`tempfile -d /tmp -p geo. -s .code`
+if [ $? -ne 0 ] || [ -z "$TMP" ] ; then
+    echo "ERROR: Unable to create temporary files" 1>&2
+    exit 1
+fi
 STYLE=${TMP}.style
 COORDS=${TMP}.coords
 OUTWAY=${TMP}.way
diff --git a/scripts/geo-nearest b/scripts/geo-nearest
--- a/scripts/geo-nearest
+++ b/scripts/geo-nearest
@@ -181,6 +181,10 @@ if [ $DEBUG -gt 0 ] ; then
     TMP=/tmp/geo
 else
     TMP=`tempfile -d /tmp -p geo. -s .nearest`
+    if [ $? -ne 0 ] || [ -z "$TMP" ] ; then
+	echo "ERROR: Unable to create temporary files" 1>&2
+	exit 1
+    fi
 fi
 TIMESTAMP="${TMP}.timestamp"
 GEOWAY="${TMP}.geocaching.loc"
